spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cagong?serverTimezone=Asia/Seoul
    username: cagong
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  mvc:
    path match:
      matching-strategy: ant_path_matcher
